from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional


class GenericBaseDriver(ABC):
    """
    Minimal base interface for all hardware drivers generated by the Agentic Factory.

    This class intentionally avoids any protocol-specific or audio-specific logic.
    Concrete drivers should remain small and composable, building behavior via
    lightweight helper objects rather than deep inheritance trees.
    """

    def __init__(self, name: str, config: Optional[Dict[str, Any]] = None) -> None:
        self._name = name
        self._config: Dict[str, Any] = config or {}

    @property
    def name(self) -> str:
        return self._name

    @property
    def config(self) -> Dict[str, Any]:
        return self._config

    def update_config(self, new_config: Dict[str, Any]) -> None:
        """
        Merge new configuration values into the existing config dictionary.
        """
        self._config.update(new_config)

    @abstractmethod
    def identify(self) -> str:
        """
        Return a short, human-readable identifier for this driver instance.
        """

    @abstractmethod
    def connect(self) -> None:
        """
        Establish any required connection to the underlying hardware or endpoint.
        """

    @abstractmethod
    def disconnect(self) -> None:
        """
        Tear down any active connections and release external resources.
        """

    @abstractmethod
    def send(self, payload: Any) -> None:
        """
        Send a single logical payload to the device.

        The concrete driver is responsible for translating this payload into the
        appropriate protocol-specific representation (e.g., UDP packets, serial
        frames, etc.).
        """

